version: '2'
services:
    ozeradb-app:
        image: ozeradb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ozeradb-postgresql:5432/ozeradb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ozeradb-postgresql:
        extends:
            file: postgresql.yml
            service: ozeradb-postgresql
